//    See https://corefork.telegram.org/type/Update
//    Derived classes: TL.UpdateNewMessage, TL.UpdateMessageID, TL.UpdateDeleteMessages,
//    TL.UpdateUserTyping, TL.UpdateChatUserTyping, TL.UpdateChatParticipants, TL.UpdateUserStatus,
//    TL.UpdateUserName, TL.UpdateNewAuthorization, TL.UpdateNewEncryptedMessage, TL.UpdateEncryptedChatTyping,
//    TL.UpdateEncryption, TL.UpdateEncryptedMessagesRead, TL.UpdateChatParticipantAdd,
//    TL.UpdateChatParticipantDelete, TL.UpdateDcOptions, TL.UpdateNotifySettings,
//    TL.UpdateServiceNotification, TL.UpdatePrivacy, TL.UpdateUserPhone, TL.UpdateReadHistoryInbox,
//    TL.UpdateReadHistoryOutbox, TL.UpdateWebPage, TL.UpdateReadMessagesContents,
//    TL.UpdateChannelTooLong, TL.UpdateChannel, TL.UpdateNewChannelMessage, TL.UpdateReadChannelInbox,
//    TL.UpdateDeleteChannelMessages, TL.UpdateChannelMessageViews, TL.UpdateChatParticipantAdmin,
//    TL.UpdateNewStickerSet, TL.UpdateStickerSetsOrder, TL.UpdateStickerSets, TL.UpdateSavedGifs,
//    TL.UpdateBotInlineQuery, TL.UpdateBotInlineSend, TL.UpdateEditChannelMessage,
//    TL.UpdateBotCallbackQuery, TL.UpdateEditMessage, TL.UpdateInlineBotCallbackQuery,
//    TL.UpdateReadChannelOutbox, TL.UpdateDraftMessage, TL.UpdateReadFeaturedStickers,
//    TL.UpdateRecentStickers, TL.UpdateConfig, TL.UpdatePtsChanged, TL.UpdateChannelWebPage,
//    TL.UpdateDialogPinned, TL.UpdatePinnedDialogs, TL.UpdateBotWebhookJSON, TL.UpdateBotWebhookJSONQuery,
//    TL.UpdateBotShippingQuery, TL.UpdateBotPrecheckoutQuery, TL.UpdatePhoneCall,
//    TL.UpdateLangPackTooLong, TL.UpdateLangPack, TL.UpdateFavedStickers, TL.UpdateChannelReadMessagesContents,
//    TL.UpdateContactsReset, TL.UpdateChannelAvailableMessages, TL.UpdateDialogUnreadMark,
//    TL.UpdateMessagePoll, TL.UpdateChatDefaultBannedRights, TL.UpdateFolderPeers,
//    TL.UpdatePeerSettings, TL.UpdatePeerLocated, TL.UpdateNewScheduledMessage, TL.UpdateDeleteScheduledMessages,
//    TL.UpdateTheme, TL.UpdateGeoLiveViewed, TL.UpdateLoginToken, TL.UpdateMessagePollVote,
//    TL.UpdateDialogFilter, TL.UpdateDialogFilterOrder, TL.UpdateDialogFilters, TL.UpdatePhoneCallSignalingData,
//    TL.UpdateChannelMessageForwards, TL.UpdateReadChannelDiscussionInbox, TL.UpdateReadChannelDiscussionOutbox,
//    TL.UpdatePeerBlocked, TL.UpdateChannelUserTyping, TL.UpdatePinnedMessages, TL.UpdatePinnedChannelMessages,
//    TL.UpdateChat, TL.UpdateGroupCallParticipants, TL.UpdateGroupCall, TL.UpdatePeerHistoryTTL,
//    TL.UpdateChatParticipant, TL.UpdateChannelParticipant, TL.UpdateBotStopped, TL.UpdateGroupCallConnection,
//    TL.UpdateBotCommands, TL.UpdatePendingJoinRequests, TL.UpdateBotChatInviteRequester,
//    TL.UpdateMessageReactions, TL.UpdateAttachMenuBots, TL.UpdateWebViewResultSent,
//    TL.UpdateBotMenuButton, TL.UpdateSavedRingtones, TL.UpdateTranscribedAudio, TL.UpdateReadFeaturedEmojiStickers,
//    TL.UpdateUserEmojiStatus, TL.UpdateRecentEmojiStatuses, TL.UpdateRecentReactions,
//    TL.UpdateMoveStickerSetToTop, TL.UpdateMessageExtendedMedia, TL.UpdateChannelPinnedTopic,
//    TL.UpdateChannelPinnedTopics, TL.UpdateUser, TL.UpdateAutoSaveSettings, TL.UpdateGroupInvitePrivacyForbidden,
//    TL.UpdateStory, TL.UpdateReadStories, TL.UpdateStoryID, TL.UpdateStoriesStealthMode,
//    TL.UpdateSentStoryReaction