// <auto-generated />
using MTProto.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTProto.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("MTProto.Core.Database.Models.OwnerPeerInfo", b =>
                {
                    b.Property<long>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER");

                    b.HasKey("OwnerId");

                    b.ToTable("OwnerInfos");
                });

            modelBuilder.Entity("MTProto.Core.Database.Models.PeerInfo", b =>
                {
                    b.Property<long>("PeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccessHash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeerId");

                    b.ToTable("PeerInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
